# Generated by Django 3.0.7 on 2021-09-05 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='', upload_to='app1/static/images'),
        ),
        migrations.AddField(
            model_name='register',
            name='blog_pk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Blog'),
        ),
    ]
