# Generated by Django 3.0.7 on 2021-09-05 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0006_auto_20210905_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='blog_pk',
        ),
        migrations.AddField(
            model_name='blog',
            name='user_pk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
